services:
  synctexts-website:
    container_name: synctexts-website
    build:
      context: .
      dockerfile: Dockerfile
    image: synctexts-website:latest
    restart: unless-stopped
    networks:
      - stack_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=stack_web"
      - "traefik.http.services.synctexts-website.loadbalancer.server.port=80"
      - "traefik.http.routers.synctexts-website-http.rule=Host(`synctexts.com`) || Host(`www.synctexts.com`)"
      - "traefik.http.routers.synctexts-website-http.entrypoints=web"
      - "traefik.http.routers.synctexts-website-http.middlewares=synctexts-website-https-redirect"
      - "traefik.http.middlewares.synctexts-website-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.synctexts-website-https.rule=Host(`synctexts.com`) || Host(`www.synctexts.com`)"
      - "traefik.http.routers.synctexts-website-https.entrypoints=websecure"
      - "traefik.http.routers.synctexts-website-https.tls=true"
      - "traefik.http.routers.synctexts-website-https.tls.certresolver=le"

networks:
  stack_web:
    external: true
